name: Create and Upload Complete Markdown Snapshot to Google Drive

on:
  push:
    branches:
      - main

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Variablen setzen
      - name: Set variables
        run: |
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
          echo "out_dir=$RUNNER_TEMP/snapshots" >> $GITHUB_ENV
          mkdir -p "$RUNNER_TEMP/snapshots"

      # 3️⃣ Markdown-Datei mit gesamtem Code erzeugen
      - name: Create FULL Markdown Snapshot
        run: |
          SNAPSHOT_FILE="recipe-vault_FULLCODE_${{ env.timestamp }}_${{ env.commit_sha }}.md"
          SNAPSHOT_PATH="${{ env.out_dir }}/${SNAPSHOT_FILE}"

          echo "# 📦 Recipe Vault – Full Source Snapshot" > "$SNAPSHOT_PATH"
          echo "" >> "$SNAPSHOT_PATH"
          echo "**Timestamp:** ${{ env.timestamp }}" >> "$SNAPSHOT_PATH"
          echo "**Commit:** ${{ env.commit_sha }}" >> "$SNAPSHOT_PATH"
          echo "" >> "$SNAPSHOT_PATH"

          echo "## 📁 Repository Structure" >> "$SNAPSHOT_PATH"
          tree -I ".git|node_modules" -a >> "$SNAPSHOT_PATH" || echo "(tree not available)" >> "$SNAPSHOT_PATH"
          echo "" >> "$SNAPSHOT_PATH"

          echo "## 🧩 Complete File Contents" >> "$SNAPSHOT_PATH"
          echo "" >> "$SNAPSHOT_PATH"

          while IFS= read -r -d '' file; do
            echo -e "\n\n### File: \`$file\`\n\`\`\`\n" >> "$SNAPSHOT_PATH"
            cat "$file" >> "$SNAPSHOT_PATH"
            echo -e "\n\`\`\`" >> "$SNAPSHOT_PATH"
          done < <(find . -type f -not -path "./.git/*" -not -path "./node_modules/*" -print0)

          echo "snapshot_file=$SNAPSHOT_FILE" >> $GITHUB_ENV
          echo "snapshot_path=$SNAPSHOT_PATH" >> $GITHUB_ENV

      # 4️⃣ Snapshot zu Google Drive hochladen
      - name: Upload Snapshot to Google Drive
        uses: adityak74/google-drive-upload-action@v1.4
        with:
          credentials: ${{ secrets.GDRIVE_SERVICE_KEY }}
          filename: ${{ env.snapshot_path }}
          folderId: ${{ secrets.GDRIVE_BASE44_FOLDER_ID }}
          name: ${{ env.snapshot_file }}

      # 5️⃣ Abschlussmeldung
      - name: Confirm upload
        run: |
          echo "✅ Snapshot successfully uploaded to Google Drive folder 'Base44'"
          echo "📄 ${{ env.snapshot_file }}"
