name: Sync from Original Base44 Repo
on:
  repository_dispatch:
    types: [upstream_updated]   # wird vom Original-Repo ausgelöst
  workflow_dispatch:            # kann manuell gestartet werden

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # --- Mirror auschecken ---
      - name: Checkout mirror repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # --- Git konfigurieren ---
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config merge.ours.driver true

      # --- Merge-Regeln sicherstellen (.gitattributes schützen & erstellen falls nötig) ---
      - name: Ensure .gitattributes merge rules
        run: |
          echo ".gitattributes merge=ours" > .gitattributes
          echo ".github/workflows/* merge=ours" >> .gitattributes
          echo "_introspection/** merge=ours" >> .gitattributes
          git add .gitattributes
          git commit -m "chore(sync): ensure merge protection rules" || true

      # --- Upstream-Repo hinzufügen und abrufen ---
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/base44dev/recipe-vault-536879b5.git || true
          git fetch upstream main

      # --- Rebase durchführen (mit Schutzregeln aus .gitattributes) ---
      - name: Rebase mirror onto upstream
        run: |
          git checkout main
          git rebase upstream/main || (
            echo "::warning ::Rebase conflict detected, aborting..."
            git rebase --abort
            exit 0
          )

      # --- Entferne Upstream-spezifische Dateien, die nicht in den Mirror gehören ---
      - name: Remove upstream-only workflow files
        run: |
          if [ -f ".github/workflows/trigger-mirror.yml" ]; then
            echo "Removing trigger-mirror.yml from mirror..."
            rm -f .github/workflows/trigger-mirror.yml
            git add -A
            git commit -m "chore(sync): remove upstream-only workflow" || true
          else
            echo "No upstream-only files to remove."
          fi

      # --- Änderungen pushen ---
      - name: Push updated mirror
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/MemoexCode/recipe-vault-mirror.git main --force
