name: Sync from Original Base44 Repo

on:
  repository_dispatch:
    types: [upstream_updated]   # wird vom Original-Repo ausgelöst
  workflow_dispatch:            # kann manuell gestartet werden

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------
      # Git vorbereiten (Merge-Treiber aktivieren, bevor rebase startet)
      # ---------------------------------------------------------
      - name: Configure Git (pre-checkout)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global merge.ours.driver true
          git config --global pull.rebase true
          git config --global advice.mergeConflict false

      # ---------------------------------------------------------
      # Mirror auschecken
      # ---------------------------------------------------------
      - name: Checkout mirror repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # ---------------------------------------------------------
      # Merge-Regeln (.gitattributes) sicherstellen
      # ---------------------------------------------------------
      - name: Ensure .gitattributes merge rules
        run: |
          echo ".gitattributes merge=ours" > .gitattributes
          echo ".github/workflows/trigger-mirror.yml merge=ours" >> .gitattributes
          echo ".github/workflows/export-tree.yml merge=ours" >> .gitattributes
          echo ".github/workflows/health-check.yml merge=ours" >> .gitattributes
          echo "_introspection/** merge=ours" >> .gitattributes
          git add .gitattributes
          git commit -m "chore(sync): ensure merge protection rules" || true

      # ---------------------------------------------------------
      # Upstream hinzufügen und abrufen (mit Token)
      # ---------------------------------------------------------
      - name: Add upstream remote
        env:
          TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git remote add upstream https://x-access-token:${TOKEN}@github.com/base44dev/recipe-vault-536879b5.git || true
          git fetch upstream main

      # ---------------------------------------------------------
      # Mirror mit Upstream abgleichen
      # ---------------------------------------------------------
      - name: Rebase mirror onto upstream
        run: |
          git checkout main
          git fetch upstream main
          git rebase upstream/main || (echo "Rebase conflict – skipping problematic commits" && git rebase --skip)

      # ---------------------------------------------------------
      # Upstream-spezifische Dateien entfernen (nur im Mirror)
      # ---------------------------------------------------------
      - name: Remove upstream-only workflow files
        run: |
          rm -f .github/workflows/trigger-mirror.yml || true
          git add .github/workflows || true
          git commit -m "chore(sync): remove upstream-only workflow" || true

      # ---------------------------------------------------------
      # Änderungen pushen
      # ---------------------------------------------------------
      - name: Push updated mirror
        env:
          TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/MemoexCode/recipe-vault-mirror.git main --force
