name: Test Dropbox Token

on:
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "This is a Dropbox upload test." > testfile.txt

      - name: Upload to Dropbox
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          echo "Uploading testfile.txt ..."
          curl -v -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $DROPBOX_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/AOp1EmihZE0GDFwgjcBh4gE/testfile_$(date +'%Y-%m-%d_%H-%M-%S').txt\",\"mode\": \"add\",\"autorename\": true}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @testfile.txt
